### PR TITLE
Feature/setup ci integration

### PR DESCRIPTION
**Pull request by baalberith**
https://github.com/amberbit/commentable/issues/2

### CODE REVIEW

**Comment by baalberith** [comment]
@hubertlepicki Ready to review

**Comment by hubertlepicki** [comment]
@baalberith I added Travis, it's configuration and travis_test.exs config file to this repo. Things should execute now on travis on each build. But something's not right, I think the database configuration in travis_test.exs is not right. We might also need to build assets before running tests (not sure).

Can you pick it up and make the build pass?

**Comment by baalberith** [comment]
@hubertlepicki Ok, I will try

**Comment by baalberith** [comment]
@hubertlepicki I think I've run out of ideas how to fix this :(

**Comment by hubertlepicki** [comment]
@baalberith I have fixed the postgresql issue. Please take over and complete it.

Postgres has been installed & configured manually. So it works. The next road block is lack of chrome & chromedriver.

Please have a look at the other project bitbucket-config.yml file to figure out how to add installation of Chrome & Chromedriver to the system :)

**Comment by hubertlepicki** [comment]
:heart: :blue_heart: :green_heart: :black_heart: :tada:

**Pull request merged**
